#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 28, 2018 11:59:35 PM IST  platform: Windows NT
import login
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import alltransaction_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    alltransaction_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    alltransaction_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font11 = "-family Arial -size 12 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+364+147")
        top.title("View-transaction")
        top.configure(background="#2c3e50")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=-0.033, rely=0.0, height=41, width=624)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''ALL TRANSACTIONS''')
        self.Label1.configure(width=624)

        self.flat_no_ts = tk.Label(top)
        self.flat_no_ts.place(relx=0.283, rely=0.133, height=21, width=114)
        self.flat_no_ts.configure(background="#d9d9d9")
        self.flat_no_ts.configure(disabledforeground="#a3a3a3")
        self.flat_no_ts.configure(foreground="#000000")
        self.flat_no_ts.configure(text='''FLAT-NO''')
        self.flat_no_ts.configure(width=114)

        self.flat_entry_ts = tk.Entry(top)
        self.flat_entry_ts.place(relx=0.567, rely=0.133, height=20
                , relwidth=0.273)
        self.flat_entry_ts.configure(background="white")
        self.flat_entry_ts.configure(disabledforeground="#a3a3a3")
        self.flat_entry_ts.configure(font="TkFixedFont")
        self.flat_entry_ts.configure(foreground="#000000")
        self.flat_entry_ts.configure(insertbackground="black")

        self.owner_name_ts = tk.Label(top)
        self.owner_name_ts.place(relx=0.283, rely=0.222, height=21, width=114)
        self.owner_name_ts.configure(background="#d9d9d9")
        self.owner_name_ts.configure(disabledforeground="#a3a3a3")
        self.owner_name_ts.configure(foreground="#000000")
        self.owner_name_ts.configure(text='''OWNER'S NAME''')
        self.owner_name_ts.configure(width=114)

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.567, rely=0.222,height=20, relwidth=0.273)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.address_ts = tk.Label(top)
        self.address_ts.place(relx=0.283, rely=0.311, height=21, width=114)
        self.address_ts.configure(background="#d9d9d9")
        self.address_ts.configure(disabledforeground="#a3a3a3")
        self.address_ts.configure(foreground="#000000")
        self.address_ts.configure(text='''ADDRESS''')
        self.address_ts.configure(width=114)

        self.Scrolledtext1 = ScrolledText(top)
        self.Scrolledtext1.place(relx=0.567, rely=0.311, relheight=0.113
                , relwidth=0.285)
        self.Scrolledtext1.configure(background="white")
        self.Scrolledtext1.configure(font="TkTextFont")
        self.Scrolledtext1.configure(foreground="black")
        self.Scrolledtext1.configure(highlightbackground="#d9d9d9")
        self.Scrolledtext1.configure(highlightcolor="black")
        self.Scrolledtext1.configure(insertbackground="black")
        self.Scrolledtext1.configure(insertborderwidth="3")
        self.Scrolledtext1.configure(selectbackground="#c4c4c4")
        self.Scrolledtext1.configure(selectforeground="black")
        self.Scrolledtext1.configure(width=10)
        self.Scrolledtext1.configure(wrap='none')

        self.security_due_ts = tk.Label(top)
        self.security_due_ts.place(relx=0.283, rely=0.489, height=21, width=114)
        self.security_due_ts.configure(background="#d9d9d9")
        self.security_due_ts.configure(disabledforeground="#a3a3a3")
        self.security_due_ts.configure(foreground="#000000")
        self.security_due_ts.configure(text='''SECURITY''')
        self.security_due_ts.configure(width=114)

        self.Entry3 = tk.Entry(top)
        self.Entry3.place(relx=0.567, rely=0.489,height=20, relwidth=0.273)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")

        self.maintance_due_ts = tk.Label(top)
        self.maintance_due_ts.place(relx=0.283, rely=0.6, height=21, width=134)
        self.maintance_due_ts.configure(background="#d9d9d9")
        self.maintance_due_ts.configure(disabledforeground="#a3a3a3")
        self.maintance_due_ts.configure(foreground="#000000")
        self.maintance_due_ts.configure(text='''MAINTAINENCE DUE''')
        self.maintance_due_ts.configure(width=134)

        self.Entry4 = tk.Entry(top)
        self.Entry4.place(relx=0.567, rely=0.6,height=20, relwidth=0.273)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")

        self.Label7 = tk.Label(top)
        self.Label7.place(relx=0.283, rely=0.8, height=31, width=114)
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''TOTAL DUE''')
        self.Label7.configure(width=114)

        self.Entry5 = tk.Entry(top)
        self.Entry5.place(relx=0.567, rely=0.8,height=30, relwidth=0.29)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(width=174)

        self.home_ts = tk.Button(top)
        self.home_ts.place(relx=0.017, rely=0.111, height=34, width=87)
        self.home_ts.configure(activebackground="#d9d9d9")
        self.home_ts.configure(activeforeground="#000000")
        self.home_ts.configure(background="#f1f1f1")
        self.home_ts.configure(disabledforeground="#a3a3a3")
        self.home_ts.configure(foreground="#000000")
        self.home_ts.configure(highlightbackground="#d9d9d9")
        self.home_ts.configure(highlightcolor="black")
        self.home_ts.configure(pady="0")
        self.home_ts.configure(text='''HOME''')
        self.home_ts.configure(width=87)

        self.serach_ts = tk.Button(top)
        self.serach_ts.place(relx=0.017, rely=0.222, height=34, width=87)
        self.serach_ts.configure(activebackground="#d9d9d9")
        self.serach_ts.configure(activeforeground="#000000")
        self.serach_ts.configure(background="#f1f1f1")
        self.serach_ts.configure(disabledforeground="#a3a3a3")
        self.serach_ts.configure(foreground="#000000")
        self.serach_ts.configure(highlightbackground="#d9d9d9")
        self.serach_ts.configure(highlightcolor="black")
        self.serach_ts.configure(pady="0")
        self.serach_ts.configure(text='''SEARCH''')

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





