#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 25, 2018 10:03:05 PM IST  platform: Windows NT

import pymysql
import sys
import home
from tkinter import messagebox
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:

    def Loginbtn(self):
        uname=self.txtuname.get()
        pass1=self.txtpassword.get()
        print(uname)
        print(pass1)
        db=pymysql.connect("localhost","root","rat","build_flats")
        cursor=db.cursor()
        sql="select * from login where uname='%s' and pass='%s'"%(uname,pass1);
        cursor.execute(sql)
        result=cursor.fetchone()
        #print(result)
        if(result):
            root.destroy()
            home.vp_start_gui()            
        else:
            messagebox.showerror("Failed", "Invalid Username Or Password!")
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font12 = "-family {Calibri Light} -size 15 -weight bold -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("600x450+312+138")
        top.title("Login")
        top.configure(background="#fff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.username = tk.Label(top)
        self.username.place(relx=0.217, rely=0.267, height=31, width=104)
        self.username.configure(activebackground="#f9f9f9")
        self.username.configure(activeforeground="black")
        self.username.configure(background="#fff")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(foreground="#000000")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="black")
        self.username.configure(text='''Username''')

        self.password = tk.Label(top)
        self.password.place(relx=0.217, rely=0.422, height=31, width=104)
        self.password.configure(activebackground="#f9f9f9")
        self.password.configure(activeforeground="black")
        self.password.configure(background="#fff")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(text='''Password''')

        self.txtuname = tk.Entry(top)
        self.txtuname.place(relx=0.517, rely=0.289,height=20, relwidth=0.273)
        self.txtuname.configure(background="white")
        self.txtuname.configure(disabledforeground="#000000")
        self.txtuname.configure(font="TkFixedFont")
        self.txtuname.configure(foreground="#e74c3c")
        self.txtuname.configure(highlightbackground="#000000")
        self.txtuname.configure(highlightcolor="black")
        self.txtuname.configure(insertbackground="black")
        self.txtuname.configure(selectbackground="#c4c4c4")
        self.txtuname.configure(selectforeground="black")
        self.txtuname.configure(width=164)

        self.txtpassword = tk.Entry(top)
        self.txtpassword.place(relx=0.517, rely=0.422, height=20, relwidth=0.273)

        self.txtpassword.configure(background="white")
        self.txtpassword.configure(disabledforeground="#a3a3a3")
        self.txtpassword.configure(font="TkFixedFont")
        self.txtpassword.configure(foreground="#e74c3c")
        self.txtpassword.configure(highlightbackground="#d9d9d9")
        self.txtpassword.configure(highlightcolor="black")
        self.txtpassword.configure(insertbackground="black")
        self.txtpassword.configure(selectbackground="#c4c4c4")
        self.txtpassword.configure(selectforeground="black")
        self.txtpassword.configure(show="*")
        self.txtpassword.configure(width=164)

        self.btnlogin = tk.Button(top, command = self.Loginbtn)
        self.btnlogin.place(relx=0.283, rely=0.622, height=24, width=97)
        self.btnlogin.configure(activebackground="#d9d9d9")
        self.btnlogin.configure(activeforeground="#000000")
        self.btnlogin.configure(background="#3498db")
        self.btnlogin.configure(disabledforeground="#a3a3a3")
        self.btnlogin.configure(foreground="#fff")
        self.btnlogin.configure(highlightbackground="#d9d9d9")
        self.btnlogin.configure(highlightcolor="black")
        self.btnlogin.configure(pady="0")
        self.btnlogin.configure(text='''LOGIN''')

        self.btnforgotpass = tk.Button(top)
        self.btnforgotpass.place(relx=0.583, rely=0.622, height=24, width=147)
        self.btnforgotpass.configure(activebackground="#d9d9d9")
        self.btnforgotpass.configure(activeforeground="#000000")
        self.btnforgotpass.configure(background="#3498db")
        self.btnforgotpass.configure(disabledforeground="")
        self.btnforgotpass.configure(foreground="#fff")
        self.btnforgotpass.configure(highlightbackground="#d9d9d9")
        self.btnforgotpass.configure(highlightcolor="black")
        self.btnforgotpass.configure(pady="0")
        self.btnforgotpass.configure(text='''FORGOT PASSWORD ?''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.0, rely=0.0, height=61, width=604)
        self.Label1.configure(background="#3498db")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font12)
        self.Label1.configure(foreground="#fff")
        self.Label1.configure(padx="20")
        self.Label1.configure(text='''LOGIN''')
        self.Label1.configure(width=604)

if __name__ == '__main__':
    vp_start_gui()





